[Definition]
actionban   = echo '{"action":"ban","ip":"<ip>","jail":"<name>","failures":"<failures>"}' \
              | socat - UNIX-CONNECT:/run/monitor-bot/bot.sock

actionunban = echo '{"action":"unban","ip":"<ip>","jail":"<name>"}' \
              | socat - UNIX-CONNECT:/run/monitor-bot/bot.sock
